version: '3'
services:
  postgres:
    image: docker.io/postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: catan
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: