spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # has overhead, not for production
    hibernate:
      ddl-auto: validate

  datasource:
    username: catan
    password:
    url: jdbc:postgresql://dpg-croo0e68ii6s73bebm60-a.frankfurt-postgres.render.com/catan_0w58

  jackson:
    default-property-inclusion: NON_NULL

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
springdoc:
  api-docs:
    path: "/api-docs"