spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # has overhead, not for production
    hibernate:
      ddl-auto: validate

  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:54321/catan

  jackson:
    default-property-inclusion: NON_NULL


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
springdoc:
  api-docs:
    path: "/api-docs"