spring:

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:54321/catan

  jackson:
    default-property-inclusion: NON_NULL


logging:
  level:
    org:
      hibernate: trace