spring:

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false

  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:54321/catan

  jackson:
    default-property-inclusion: NON_NULL