name: Build and push image to github registry
on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: 'Verify project'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 'Build and test'
        run: mvn -B verify


  deploy:
    name: 'Deploy to Github Container Registry'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 'Log to ghcr.io'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: 'Deploy'
        run: |
          mvn -B compile jib:build  \
          -Dimage=ghcr.io/${{ github.repository }}-${{ github.ref }}:latest